name: clean
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to 
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
#  Service Locator
  get_it: ^7.2.0
   # state managment 
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_icons: ^1.1.0
  firebase_auth: ^4.2.2
  
  # Firebase
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  firebase_core: ^2.9.0

  flutter_svg: ^2.0.4
  image_picker: ^0.8.7+1
  intl: ^0.18.0
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  flutter_toastr: ^1.0.3
  bottom_sheet: ^3.1.2
  modal_bottom_sheet: ^2.1.2
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  mockito: ^5.4.0

flutter:


  uses-material-design: true


  assets:
    - assets/svg/
    - assets/
  

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

